"""allow_null_audios

Revision ID: dfbe88d306bf
Revises: f032a4981de2
Create Date: 2025-03-22 16:33:34.315804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfbe88d306bf'
down_revision: Union[str, None] = 'f032a4981de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audios', sa.Column('is_audio_valid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audios', 'is_audio_valid')
    # ### end Alembic commands ###
