"""create_process_media

Revision ID: 4cc9b9d40821
Revises: 2e8350845ca0
Create Date: 2025-03-22 15:38:35.223219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc9b9d40821'
down_revision: Union[str, None] = '2e8350845ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('providers_transcription', sa.Integer(), nullable=True),
    sa.Column('providers_translation', sa.Integer(), nullable=True),
    sa.Column('providers_generation', sa.Integer(), nullable=True),
    sa.Column('languages_from', sa.Integer(), nullable=True),
    sa.Column('languages_to', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DONE', 'FAIL', 'PROCESS', name='statustype'), nullable=False),
    sa.ForeignKeyConstraint(['audio_id'], ['audios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['languages_from'], ['languages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['languages_to'], ['languages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['providers_generation'], ['providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['providers_transcription'], ['providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['providers_translation'], ['providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_media_id'), 'process_media', ['id'], unique=False)
    op.alter_column('scores', 'total_translations',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('scores', 'total_languages_used',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('scores', 'total_users_translations',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('scores', 'total_system_languages',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('scores', 'different_users_contacted',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('scores', 'total_system_users',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('scores', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               nullable=True)
    op.drop_index('ix_scores_user_id', table_name='scores')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_scores_user_id', 'scores', ['user_id'], unique=False)
    op.alter_column('scores', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               nullable=False)
    op.alter_column('scores', 'total_system_users',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('scores', 'different_users_contacted',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('scores', 'total_system_languages',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('scores', 'total_users_translations',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('scores', 'total_languages_used',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('scores', 'total_translations',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.drop_index(op.f('ix_process_media_id'), table_name='process_media')
    op.drop_table('process_media')
    # ### end Alembic commands ###
