"""Create tts_providers table

Revision ID: 126007a0caab
Revises: 5e6d1e82b884
Create Date: 2025-02-12 19:29:11.960465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126007a0caab'
down_revision: Union[str, None] = '5e6d1e82b884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tts_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tts_providers_id'), 'tts_providers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tts_providers_id'), table_name='tts_providers')
    op.drop_table('tts_providers')
    # ### end Alembic commands ###
