"""Create translation_providers table

Revision ID: 334b9c270030
Revises: ca5a61ea27e7
Create Date: 2025-02-12 15:17:48.004958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334b9c270030'
down_revision: Union[str, None] = 'ca5a61ea27e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_translation_providers_id'), 'translation_providers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_providers_id'), table_name='translation_providers')
    op.drop_table('translation_providers')
    # ### end Alembic commands ###
