"""Create Process_media table

Revision ID: 96da406450bd
Revises: 2e8350845ca0
Create Date: 2025-03-19 16:35:21.269197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = '96da406450bd'
down_revision: Union[str, None] = '2e8350845ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

status_enum = ENUM('DONE', 'FAIL', 'PROCESS', name='status_type', create_type=True)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Crear la tabla process_media
    op.create_table(
        'process_media',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('audio_id', sa.Integer, sa.ForeignKey("audios.id", ondelete="CASCADE"), nullable=False),
        sa.Column('user_id', sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column('providers_transcription', sa.Integer, sa.ForeignKey("providers.id", ondelete="SET NULL")),
        sa.Column('providers_translation', sa.Integer, sa.ForeignKey("providers.id", ondelete="SET NULL")),
        sa.Column('providers_generation', sa.Integer, sa.ForeignKey("providers.id", ondelete="SET NULL")),
        sa.Column('languages_from', sa.Integer, sa.ForeignKey("languages.id", ondelete="SET NULL")),
        sa.Column('languages_to', sa.Integer, sa.ForeignKey("languages.id", ondelete="SET NULL")),
        sa.Column('status', status_enum, nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process_media')

    status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
