"""add atributtes user_id, transcription and language in AudioRecord

Revision ID: e52ad27d09d3
Revises: 097d698c41f3
Create Date: 2025-01-30 07:44:16.761226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52ad27d09d3'
down_revision: Union[str, None] = '097d698c41f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audios', sa.Column('user_id', sa.String(length=255), nullable=False))
    op.add_column('audios', sa.Column('transcription', sa.Text(), nullable=True))
    op.add_column('audios', sa.Column('language', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_audios_user_id'), 'audios', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audios_user_id'), table_name='audios')
    op.drop_column('audios', 'language')
    op.drop_column('audios', 'transcription')
    op.drop_column('audios', 'user_id')
    # ### end Alembic commands ###
