"""fix_null_audios

Revision ID: dfb8fd6f6e1f
Revises: dfbe88d306bf
Create Date: 2025-03-22 16:48:16.192044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb8fd6f6e1f'
down_revision: Union[str, None] = 'dfbe88d306bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audios', sa.Column('validation_error', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audios', 'validation_error')
    # ### end Alembic commands ###
