"""Create translated_audios table

Revision ID: fe8362beb43d
Revises: e52ad27d09d3
Create Date: 2025-02-05 17:24:25.778863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8362beb43d'
down_revision: Union[str, None] = 'e52ad27d09d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'translated_audios',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('audio_id', sa.Integer, sa.ForeignKey('audios.id'), nullable=False),
        sa.Column('audio_data', sa.LargeBinary),
        sa.Column('file_size', sa.Integer),
        sa.Column('language', sa.String(50)),
        sa.Column('transcription', sa.Text, nullable=True),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now(), nullable=False)
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translated_audios')
    # ### end Alembic commands ###
