"""users table

Revision ID: ad7c6c9aa804
Revises: ec2b4ea51efb
Create Date: 2025-02-28 13:44:12.195300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7c6c9aa804'
down_revision: Union[str, None] = 'ec2b4ea51efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('email', sa.String(length=256), nullable=False, primary_key=True),
        sa.Column('password_hash', sa.Text(), nullable=False),
        sa.Column('first_name', sa.String(length=256), nullable=False),
        sa.Column('last_name', sa.String(length=256), nullable=False),
        sa.Column('last_login', sa.DateTime(), nullable=True),
        sa.Column('is_activate', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
