"""Create Score table

Revision ID: 2e8350845ca0
Revises: 3a58ab680a03
Create Date: 2025-03-18 22:09:02.982904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8350845ca0'
down_revision: Union[str, None] = '3a58ab680a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'scores',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column('total_translations', sa.Integer, nullable=False, server_default="0"),
        sa.Column('total_languages_used', sa.Integer, nullable=False, server_default="0"),
        sa.Column('total_users_translations', sa.Integer, nullable=False, server_default="0"),
        sa.Column('total_system_languages', sa.Integer, nullable=False, server_default="0"),
        sa.Column('different_users_contacted', sa.Integer, nullable=False, server_default="0"),
        sa.Column('total_system_users', sa.Integer, nullable=False, server_default="0"),
        sa.Column('score', sa.Float, nullable=False, server_default="0"),
        sa.Column('last_updated', sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now())
    )
    op.create_index(op.f('ix_scores_user_id'), 'scores', ['user_id'], unique=False)
    op.create_foreign_key(None, 'scores', 'users', ['user_id'], ['id'], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.drop_index(op.f('ix_scores_user_id'), table_name='scores')
    op.drop_table('scores')
    # ### end Alembic commands ###
