"""update in table audios user_id to foreign key

Revision ID: b35045407360
Revises: ad7c6c9aa804
Create Date: 2025-02-28 17:05:15.935527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b35045407360'
down_revision: Union[str, None] = 'ad7c6c9aa804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Primero, eliminar cualquier restricción previa (si existe)
    # Eliminar la restricción previa si existe
    
    # Asegurar que user_id tenga el tipo correcto
    op.alter_column('audios', 'user_id',
        existing_type=sa.Integer(),
        nullable=False  # Cambiar a True si quieres permitir valores NULL
    )
    
    # Agregar la clave foránea
    op.create_foreign_key(
        'audios_users_id_fk',  # Nombre de la FK
        'audios',           # Tabla modificada
        'users',            # Tabla referenciada
        ['user_id'],        # Columna en "audios"
        ['id'],             # Columna en "users"
        ondelete="CASCADE"  # Opcional: elimina en cascada si se borra un usuario
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """Revertir la migración"""
    op.drop_constraint('audios_users_id_fk', 'audios', type_='foreignkey')
    op.alter_column('audios', 'user_id',
        existing_type=sa.Integer(),
        nullable=True  # Restaurar el estado anterior si permitía NULL
    )
    # ### end Alembic commands ###
