"""languages table

Revision ID: 0d33e2f9fefc
Revises: fe8362beb43d
Create Date: 2025-02-11 01:52:54.135138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d33e2f9fefc'
down_revision: Union[str, None] = 'fe8362beb43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audios', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('translated_audios', 'audio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('translated_audios', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_translated_audios_id'), 'translated_audios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translated_audios_id'), table_name='translated_audios')
    op.alter_column('translated_audios', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('translated_audios', 'audio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('audios', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
